server:
  ssl:
    key-store-password: password
    key-store-type: pkcs12
    key-store: classpath:eleicao-online.p12
    key-alias: eleicao-online
    key-password: password
  servlet:
    context-path: /
  port: '8443'
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 259386876073723
            client-secret: 5afd0c5332e985a744997b49d5f1956a
          google:
            client-secret: gKYvpzIYPq989xXuHHBaqy1H
            client-id: 604673876847-j978ar4hnu3uj7kvmu357vabco0d2nvc.apps.googleusercontent.com
jwt:
  secret: HjN784
