/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.model.Candidato;
import io.swagger.model.Erro;
import io.swagger.model.FiltroPessoa;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-09-28T03:34:36.276Z[GMT]")
@Validated
public interface CandidatoApi {

    @Operation(summary = "Atualiza um candidato", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "candidato" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Candidato.class))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/candidato",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Candidato> atualizarCandidato(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto candidato que precisa ser atualizado", required=true, schema=@Schema()) @Valid @RequestBody Candidato body);


    @Operation(summary = "Busca o candidato pelo id", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "candidato" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Candidato.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Candidato não encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/candidato/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Candidato> buscarCandidatoPeloId(@Parameter(in = ParameterIn.PATH, description = "Id do candidato buscado", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Buscar candidatos por filtro", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "candidato" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Candidato.class)))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Nenhum resultado encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/candidato/filtro",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<Candidato>> buscarCandidatosPorFiltro(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto filtro para restringir a busca", required=true, schema=@Schema()) @Valid @RequestBody FiltroPessoa body);


    @Operation(summary = "Cadastrar um novo candidato", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "candidato" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Candidato.class))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/candidato",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Candidato> cadastrarCandidato(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto candidato que precisa ser cadastrado", required=true, schema=@Schema()) @Valid @RequestBody Candidato body);


    @Operation(summary = "Remove o candidato", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "candidato" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso"),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Candidato não encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/candidato/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removerCandidato(@Parameter(in = ParameterIn.PATH, description = "Id do candidato a ser removido", required=true, schema=@Schema()) @PathVariable("id") Long id);

}

