/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.model.Configuracao;
import io.swagger.model.Eleicao;
import io.swagger.model.Erro;
import io.swagger.model.FiltroEleicao;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-09-28T03:34:36.276Z[GMT]")
@Validated
public interface EleicaoApi {

    @Operation(summary = "Atualiza uma eleicao", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Eleicao.class))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Eleicao> atualizarEleicao(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto eleicao que precisa ser atualizado", required=true, schema=@Schema()) @Valid @RequestBody Eleicao body);


    @Operation(summary = "Busca a eleicao pelo id", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Eleicao.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Eleição não encontrada", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Eleicao> buscarEleicaoPeloId(@Parameter(in = ParameterIn.PATH, description = "Id da eleicao buscada", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Buscar eleições por filtro", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Eleicao.class)))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Nenhum resultado encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao/filtro",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<Eleicao>> buscarEleicoesPorFiltro(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto filtro para restringir a busca", required=true, schema=@Schema()) @Valid @RequestBody FiltroEleicao body);


    @Operation(summary = "Busca a estatística da eleicao", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Eleição não encontrada", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao/estatistica/{idEleicao}/{tipoEstatistica}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Object>> buscarEstatistiscaEleicao(@Parameter(in = ParameterIn.PATH, description = "Id da eleicao ao qual a estatística está associada", required=true, schema=@Schema()) @PathVariable("idEleicao") Long idEleicao, @Parameter(in = ParameterIn.PATH, description = "Tipo da estatística", required=true, schema=@Schema()) @PathVariable("tipoEstatistica") Integer tipoEstatistica);


    @Operation(summary = "Cadastrar uma nova eleicao", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Eleicao.class))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Eleicao> cadastrarEleicao(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto eleicao que precisa ser cadastrado", required=true, schema=@Schema()) @Valid @RequestBody Eleicao body);


    @Operation(summary = "Configura uma eleicao", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Configuracao.class))),
        
        @ApiResponse(responseCode = "400", description = "Entrada inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao/configuracao",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Configuracao> configurarEleicao(@Parameter(in = ParameterIn.DEFAULT, description = "Objeto configurado que precisa ser criado", required=true, schema=@Schema()) @Valid @RequestBody Configuracao body);


    @Operation(summary = "Lista as eleições", description = "", tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Eleicao.class)))),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Nenhum resultado encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "501", description = "Sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Eleicao.class)))) })
    @RequestMapping(value = "/eleicao",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Eleicao>> listarEleicoes();


    @Operation(summary = "Remove a eleicao", description = "", security = {
        @SecurityRequirement(name = "eleicaoonline_auth", scopes = {
            "administrador",
"comissao",
"eleitor"        })    }, tags={ "eleicao" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Sucesso"),
        
        @ApiResponse(responseCode = "401", description = "Usuário não autorizado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "404", description = "Eleição não encontrada", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "409", description = "Erro de negócio", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))),
        
        @ApiResponse(responseCode = "500", description = "Erro de sistema", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Erro.class))) })
    @RequestMapping(value = "/eleicao/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removerEleicao(@Parameter(in = ParameterIn.PATH, description = "Id da eleicao a ser removido", required=true, schema=@Schema()) @PathVariable("id") Long id);

}

